name: Build for WebGL and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Rust
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli --version 0.2.88
          cargo update -p wasm-bindgen --precise 0.2.88

      - name: Build
        env:
          WASM_BUILD: 1
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-name game \
            --out-dir target \
            --target web target/wasm32-unknown-unknown/release/try-rust-bevy.wasm

      - name: Upload Files
        uses: actions/upload-artifact@v3
        with:
          name: game_artifact
          path: |
            target/game.js
            target/game_bg.wasm

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git fetch
          git switch gh-pages

      - name: Download Files
        uses: actions/download-artifact@v3
        with:
          name: game_artifact

      - name: Deploy to GitHub Pages
        run: |
          mv game.js assets/js/game.js
          mv game_bg.wasm assets/js/game_bg.wasm
          git add assets/js/game.js
          git add assets/js/game_bg.wasm
          git commit -m "build"
          git push -f origin gh-pages
